### ISSUE TITLE
Latest release (0.13.0.1) doesn't compile with boost 1.66

### ISSUE THREAD

**Issue by apocsurvivor** [zoinofficial/zoin#27]
Just tried to compile the latest release 0.13.0.1 on OpenSuse tumbleweed using Boost 1.66 and it fails.

**/usr/include/boost/multi_index/detail/ord_index_impl.hpp:1181:7: error: no match for call to ‘(const key_compare {aka const CompareModifiedEntry}) (const CTxMemPoolModifiedEntry&, CTxMemPoolModifiedEntry&)’**
       if(comp_(key(v),key(y->value())))return false;
       ^~
In file included from miner.cpp:6:0:
miner.h:79:10: note: candidate: bool CompareModifiedEntry::operator()(const CTxMemPoolModifiedEntry&, const CTxMemPoolModifiedEntry&) <near match>
     bool operator()(const CTxMemPoolModifiedEntry &a, const CTxMemPoolModifiedEntry &b)
          ^~~~~~~~
miner.h:79:10: note:   passing ‘const key_compare* {aka const CompareModifiedEntry*}’ as ‘this’ argument discards qualifiers
In file included from /usr/include/boost/multi_index/ordered_index.hpp:17:0,
                 from txmempool.h:21,
                 from miner.h:10,
                 from miner.cpp:6:
**/usr/include/boost/multi_index/detail/ord_index_impl.hpp:1186:25: error: no match for call to ‘(const key_compare {aka const CompareModifiedEntry}) (CTxMemPoolModifiedEntry&, const CTxMemPoolModifiedEntry&)’**
     return y==header()||!comp_(key(y->value()),key(v));
In file included from miner.cpp:6:0:
miner.h:79:10: note: candidate: bool CompareModifiedEntry::operator()(const CTxMemPoolModifiedEntry&, const CTxMemPoolModifiedEntry&) <near match>
     bool operator()(const CTxMemPoolModifiedEntry &a, const CTxMemPoolModifiedEntry &b)
          ^~~~~~~~
miner.h:79:10: note:   passing ‘const key_compare* {aka const CompareModifiedEntry*}’ as ‘this’ argument discards qualifiers
In file included from chain.h:12:0,
                 from miner.cpp:9:

**Comment by apocsurvivor** [comment]
I've just tried this again now with the next version 0.13.0.2 and that error seems to be fixed. I've got a different error building the qt wallet interface. Should I post that as a separate issue?

**Comment by mattt21** [comment]
Yes please
